workflows:
  android-build:
    name: Build Android APK
    environment:
      flutter: "3.13.9"  # ✅ Compatível com AGP 7.3.0
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
